### PR TITLE
Fix CMake error on Linux …

### PR DESCRIPTION
**Pull request by Knitschi**
…caused by missing PUBLIC keyword in target_link_libraries() call.

### CODE REVIEW

**Comment by Knitschi** [comment]
Problem is mentioned in [issue 3](hunter-packages/googletest#3).

**Comment by Knitschi** [comment]
The problem got its own [issue](hunter-packages/googletest#5)

**Comment by ruslo** [comment]
@Knitschi I've already openned pull request: https://github.com/hunter-packages/googletest/pull/5 feel free to merge and release

**Comment by Knitschi** [comment]
But why does the buld fail?

**Comment by ruslo** [comment]
re:{But why does the buld fail?} now it doesn't, this patch make is works

**Comment by ruslo** [comment]
Closing in favor of https://github.com/hunter-packages/googletest/pull/5

**Pull request closed without merging**
