### PR TITLE
Merge upstream/master to googletest/hunter

### PR DESCRIPTION
**Pull request by Predelnik**
Mostly because it fails to compile on newer version of MSVC2017.
I hope I got conflict resolution right but maybe not.

### CODE REVIEW

**Comment by ruslo** [comment]
> I hope I got conflict resolution right but maybe not.

Let's see what tests will show.

Released: https://github.com/hunter-packages/googletest/releases/tag/1.8.0-hunter-p11

**Comment by Knitschi** [comment]
I saw that you removed the following lines in the `CMakeLists.txt` files from the original googletest starting at line 104:

```cmake
# If the CMake version supports it, attach header directory information
# to the targets for when we are part of a parent build (ie being pulled
# in via add_subdirectory() rather than being a standalone build).
if (DEFINED CMAKE_VERSION AND NOT "${CMAKE_VERSION}" VERSION_LESS "2.8.11")
  target_include_directories(gtest      SYSTEM INTERFACE "${gtest_SOURCE_DIR}/include")
  target_include_directories(gtest_main SYSTEM INTERFACE "${gtest_SOURCE_DIR}/include")
endif()
```

Was this intentionally or an accident? The comment indicates that we do not need them in a hunter package, but I think we should make as view changes as possible to the original version. But as it is already merged I think we can leave it as is, as long as nobody complains.

**Comment by ruslo** [comment]
> target_include_directories(gtest SYSTEM INTERFACE "${gtest_SOURCE_DIR}/include")

Just for the record this is not correct in general. You should never put full path to PUBLIC/INTERFACE includes. It's an error with or without Hunter. Fix is to use `$<BUILD_INTERFACE:...>`.

**Comment by Predelnik** [comment]
@Knitschi 
I believe that they were removed before my merge due to 35d5f03cd0960 so I decided to keep it that way. The merge conflicts was there because these lines changed a bit in upstream but they weren't fixed like in comment by @ruslo so CMake was complaining. I think that would be good thing to push `$<BUILD_INTERFACE:...>` stuff to upstream and keep them but can't promise to follow through on that :)

**Comment by Knitschi** [comment]
Ok ok I shut up. I guess ruslan told me back then to remove the stuff.

**Pull request merged**
